// Starter data

export const defaultItems = [
  // Produce (8 items)
  {
    id: 1,
    name: "Apples",
    category: "produce",
    quantity: 45,
    notes: "Red Delicious",
    image: "apples.jpg",
  },
  {
    id: 2,
    name: "Bananas",
    category: "produce",
    quantity: 60,
    notes: "Fresh bunches",
    image: "bananas.jpg",
  },
  {
    id: 3,
    name: "Carrots",
    category: "produce",
    quantity: 30,
    notes: "1lb bags",
    image: "carrots.jpg",
  },
  {
    id: 4,
    name: "Potatoes",
    category: "produce",
    quantity: 50,
    notes: "Russet, 5lb bags",
    image: "potatoes.jpg",
  },
  {
    id: 5,
    name: "Tomatoes",
    category: "produce",
    quantity: 25,
    notes: "Roma tomatoes",
    image: "tomatoes.jpg",
  },
  {
    id: 6,
    name: "Lettuce",
    category: "produce",
    quantity: 20,
    notes: "Iceberg lettuce heads",
    image: "lettuce.jpg",
  },
  {
    id: 7,
    name: "Onions",
    category: "produce",
    quantity: 35,
    notes: "Yellow onions, 2lb bags",
    image: "onions.jpg",
  },
  {
    id: 8,
    name: "Bell Peppers",
    category: "produce",
    quantity: 18,
    notes: "Mixed colors",
    image: "bell-peppers.jpg",
  },

  // Meat (8 items)
  {
    id: 9,
    name: "Ground Beef",
    category: "meat",
    quantity: 15,
    notes: "1lb frozen packages",
    image: "ground-beef.jpg",
  },
  {
    id: 10,
    name: "Chicken Breast",
    category: "meat",
    quantity: 20,
    notes: "Boneless, frozen",
    image: "chicken-breast.jpg",
  },
  {
    id: 11,
    name: "Pork Chops",
    category: "meat",
    quantity: 12,
    notes: "Family packs, frozen",
    image: "pork-chops.jpg",
  },
  {
    id: 12,
    name: "Turkey",
    category: "meat",
    quantity: 8,
    notes: "Whole frozen turkey",
    image: "turkey.jpg",
  },
  {
    id: 13,
    name: "Bacon",
    category: "meat",
    quantity: 10,
    notes: "1lb packages",
    image: "bacon.jpg",
  },
  {
    id: 14,
    name: "Hot Dogs",
    category: "meat",
    quantity: 25,
    notes: "Beef franks",
    image: "hot-dogs.jpg",
  },
  {
    id: 15,
    name: "Ground Turkey",
    category: "meat",
    quantity: 14,
    notes: "Lean, 1lb packages",
    image: "ground-turkey.jpg",
  },
  {
    id: 16,
    name: "Sausage Links",
    category: "meat",
    quantity: 18,
    notes: "Breakfast sausage",
    image: "sausage-links.jpg",
  },

  // Dairy (8 items)
  {
    id: 17,
    name: "Milk",
    category: "dairy",
    quantity: 30,
    notes: "Whole milk, 1 gallon",
    image: "milk.jpg",
  },
  {
    id: 18,
    name: "Eggs",
    category: "dairy",
    quantity: 40,
    notes: "Grade A large, dozen",
    image: "eggs.jpg",
  },
  {
    id: 19,
    name: "Cheddar Cheese",
    category: "dairy",
    quantity: 22,
    notes: "Shredded, 8oz",
    image: "cheddar.jpg",
  },
  {
    id: 20,
    name: "Yogurt",
    category: "dairy",
    quantity: 35,
    notes: "Assorted flavors",
    image: "yogurt.jpg",
  },
  {
    id: 21,
    name: "Butter",
    category: "dairy",
    quantity: 15,
    notes: "Salted, 1lb",
    image: "butter.jpg",
  },
  {
    id: 22,
    name: "Sour Cream",
    category: "dairy",
    quantity: 12,
    notes: "16oz containers",
    image: "sour-cream.jpg",
  },
  {
    id: 23,
    name: "Cream Cheese",
    category: "dairy",
    quantity: 18,
    notes: "8oz blocks",
    image: "cream-cheese.jpg",
  },
  {
    id: 24,
    name: "Mozzarella",
    category: "dairy",
    quantity: 20,
    notes: "Shredded, 8oz",
    image: "mozzarella.jpg",
  },

  // Canned Goods (8 items)
  {
    id: 25,
    name: "Canned Beans",
    category: "canned",
    quantity: 50,
    notes: "Black beans, 15oz",
    image: "black-beans.jpg",
  },
  {
    id: 26,
    name: "Canned Corn",
    category: "canned",
    quantity: 45,
    notes: "Whole kernel, 15oz",
    image: "corn.jpg",
  },
  {
    id: 27,
    name: "Tomato Sauce",
    category: "canned",
    quantity: 40,
    notes: "15oz cans",
    image: "tomato-sauce.jpg",
  },
  {
    id: 28,
    name: "Canned Tuna",
    category: "canned",
    quantity: 35,
    notes: "Chunk light, 5oz",
    image: "canned-tuna.jpg",
  },
  {
    id: 29,
    name: "Chicken Soup",
    category: "canned",
    quantity: 30,
    notes: "Condensed, 10.5oz",
    image: "chicken-soup.jpg",
  },
  {
    id: 30,
    name: "Canned Peas",
    category: "canned",
    quantity: 28,
    notes: "Sweet peas, 15oz",
    image: "canned-peas.jpg",
  },
  {
    id: 31,
    name: "Canned Peaches",
    category: "canned",
    quantity: 25,
    notes: "In light syrup, 15oz",
    image: "canned-peaches.jpg",
  },
  {
    id: 32,
    name: "Tomato Paste",
    category: "canned",
    quantity: 32,
    notes: "6oz cans",
    image: "tomato-paste.jpg",
  },

  // Grains & Pasta (8 items)
  {
    id: 33,
    name: "White Rice",
    category: "grains",
    quantity: 25,
    notes: "Long grain, 2lb bags",
    image: "white-rice.jpg",
  },
  {
    id: 34,
    name: "Spaghetti",
    category: "grains",
    quantity: 40,
    notes: "1lb boxes",
    image: "spaghetti.jpg",
  },
  {
    id: 35,
    name: "Oatmeal",
    category: "grains",
    quantity: 22,
    notes: "Quick oats, 18oz",
    image: "oatmeal.jpg",
  },
  {
    id: 36,
    name: "Cereal",
    category: "grains",
    quantity: 30,
    notes: "Assorted varieties",
    image: "cereal.jpg",
  },
  {
    id: 37,
    name: "Penne",
    category: "grains",
    quantity: 35,
    notes: "1lb boxes",
    image: "penne.jpg",
  },
  {
    id: 38,
    name: "Macaroni",
    category: "grains",
    quantity: 28,
    notes: "Elbow pasta, 1lb",
    image: "macaroni.jpg",
  },
  {
    id: 39,
    name: "Quinoa",
    category: "grains",
    quantity: 15,
    notes: "Organic, 1lb bags",
    image: "quinoa.jpg",
  },
  {
    id: 40,
    name: "Brown Rice",
    category: "grains",
    quantity: 18,
    notes: "2lb bags",
    image: "brown-rice.jpg",
  },

  // Bakery (8 items)
  {
    id: 41,
    name: "Sandwich Bread",
    category: "bakery",
    quantity: 30,
    notes: "White bread loaves",
    image: "white-bread.jpg",
  },
  {
    id: 42,
    name: "Hamburger Buns",
    category: "bakery",
    quantity: 20,
    notes: "8-pack",
    image: "hamburger-buns.jpg",
  },
  {
    id: 43,
    name: "Hot Dog Buns",
    category: "bakery",
    quantity: 18,
    notes: "8-pack",
    image: "hot-dog-buns.jpg",
  },
  {
    id: 44,
    name: "Bagels",
    category: "bakery",
    quantity: 15,
    notes: "Plain, 6-pack",
    image: "bagels.jpg",
  },
  {
    id: 45,
    name: "English Muffins",
    category: "bakery",
    quantity: 12,
    notes: "6-pack",
    image: "english-muffins.jpg",
  },
  {
    id: 46,
    name: "Tortillas",
    category: "bakery",
    quantity: 25,
    notes: "Flour, 10-count",
    image: "tortillas.jpg",
  },
  {
    id: 47,
    name: "Dinner Rolls",
    category: "bakery",
    quantity: 14,
    notes: "12-pack",
    image: "dinner-rolls.jpg",
  },
  {
    id: 48,
    name: "Pita Bread",
    category: "bakery",
    quantity: 10,
    notes: "Whole wheat, 6-pack",
    image: "pita-bread.jpg",
  },

  // Frozen Foods (8 items)
  {
    id: 49,
    name: "Frozen Pizza",
    category: "frozen",
    quantity: 20,
    notes: "Pepperoni, 12 inch",
    image: "frozen-pizza.jpg",
  },
  {
    id: 50,
    name: "Frozen Vegetables",
    category: "frozen",
    quantity: 35,
    notes: "Mixed veggies, 16oz",
    image: "frozen-vegetables.jpg",
  },
  {
    id: 51,
    name: "Ice Cream",
    category: "frozen",
    quantity: 15,
    notes: "Vanilla, 1.5qt",
    image: "ice-cream.jpg",
  },
  {
    id: 52,
    name: "Frozen Fries",
    category: "frozen",
    quantity: 22,
    notes: "Crinkle cut, 2lb",
    image: "frozen-fries.jpg",
  },
  {
    id: 53,
    name: "Frozen Berries",
    category: "frozen",
    quantity: 18,
    notes: "Mixed berries, 12oz",
    image: "frozen-berries.jpg",
  },
  {
    id: 54,
    name: "Frozen Waffles",
    category: "frozen",
    quantity: 16,
    notes: "Homestyle, 10-count",
    image: "frozen-waffles.jpg",
  },
  {
    id: 55,
    name: "Frozen Chicken Nuggets",
    category: "frozen",
    quantity: 20,
    notes: "Breaded, 2lb",
    image: "frozen-chicken-nuggets.jpg",
  },
  {
    id: 56,
    name: "Frozen Burritos",
    category: "frozen",
    quantity: 25,
    notes: "Bean & cheese",
    image: "frozen-burritos.jpg",
  },

  // Beverages (8 items)
  {
    id: 57,
    name: "Orange Juice",
    category: "beverages",
    quantity: 20,
    notes: "100% juice, 64oz",
    image: "orange-juice.jpg",
  },
  {
    id: 58,
    name: "Apple Juice",
    category: "beverages",
    quantity: 18,
    notes: "100% juice, 64oz",
    image: "apple-juice.jpg",
  },
  {
    id: 59,
    name: "Coffee",
    category: "beverages",
    quantity: 15,
    notes: "Ground coffee, 12oz",
    image: "coffee.jpg",
  },
  {
    id: 60,
    name: "Tea Bags",
    category: "beverages",
    quantity: 22,
    notes: "Black tea, 100-count",
    image: "tea.jpg",
  },
  {
    id: 61,
    name: "Sports Drinks",
    category: "beverages",
    quantity: 30,
    notes: "Assorted flavors, 32oz",
    image: "sports-drinks.jpg",
  },
  {
    id: 62,
    name: "Bottled Water",
    category: "beverages",
    quantity: 50,
    notes: "24-pack, 16.9oz bottles",
    image: "water.jpg",
  },
  {
    id: 63,
    name: "Soda",
    category: "beverages",
    quantity: 25,
    notes: "Cola, 2-liter bottles",
    image: "cola.jpg",
  },
  {
    id: 64,
    name: "Fruit Punch",
    category: "beverages",
    quantity: 20,
    notes: "Powder mix, makes 8qt",
    image: "fruit-punch.jpg",
  },

  // Personal Care (8 items)
  {
    id: 65,
    name: "Toothpaste",
    category: "personal-care",
    quantity: 30,
    notes: "Fluoride, 6oz tubes",
    image: "toothpaste.jpg",
  },
  {
    id: 66,
    name: "Toothbrush",
    category: "personal-care",
    quantity: 40,
    notes: "Adult soft bristle",
    image: "toothbrush.jpg",
  },
  {
    id: 67,
    name: "Shampoo",
    category: "personal-care",
    quantity: 22,
    notes: "Family size, 28oz",
    image: "shampoo.jpg",
  },
  {
    id: 68,
    name: "Soap Bars",
    category: "personal-care",
    quantity: 35,
    notes: "3-pack bars",
    image: "soap-bars.jpg",
  },
  {
    id: 69,
    name: "Deodorant",
    category: "personal-care",
    quantity: 18,
    notes: "Antiperspirant, 2.6oz",
    image: "deodorant.jpg",
  },
  {
    id: 70,
    name: "Tissues",
    category: "personal-care",
    quantity: 25,
    notes: "Facial tissues, 160-count",
    image: "tissues.jpg",
  },
  {
    id: 71,
    name: "Toilet Paper",
    category: "personal-care",
    quantity: 30,
    notes: "12 double rolls",
    image: "toilet-paper.jpg",
  },
  {
    id: 72,
    name: "Hand Sanitizer",
    category: "personal-care",
    quantity: 28,
    notes: "8oz bottles",
    image: "hand-sanitizer.jpg",
  },

  // Household Supplies (8 items)
  {
    id: 73,
    name: "Dish Soap",
    category: "household",
    quantity: 20,
    notes: "Liquid, 24oz",
    image: "dish-soap.jpg",
  },
  {
    id: 74,
    name: "Laundry Detergent",
    category: "household",
    quantity: 15,
    notes: "Liquid, 64oz",
    image: "laundry-detergent.jpg",
  },
  {
    id: 75,
    name: "Paper Towels",
    category: "household",
    quantity: 25,
    notes: "6-pack rolls",
    image: "paper-towels.jpg",
  },
  {
    id: 76,
    name: "Trash Bags",
    category: "household",
    quantity: 18,
    notes: "13 gallon, 40-count",
    image: "trash-bags.jpg",
  },
  {
    id: 77,
    name: "Aluminum Foil",
    category: "household",
    quantity: 12,
    notes: "75 sq ft roll",
    image: "aluminum-foil.jpg",
  },
  {
    id: 78,
    name: "Plastic Wrap",
    category: "household",
    quantity: 14,
    notes: "200 sq ft roll",
    image: "plastic-wrap.jpg",
  },
  {
    id: 79,
    name: "Sponges",
    category: "household",
    quantity: 30,
    notes: "Scrub sponges, 6-pack",
    image: "sponges.jpg",
  },
  {
    id: 80,
    name: "All-Purpose Cleaner",
    category: "household",
    quantity: 16,
    notes: "Spray bottle, 32oz",
    image: "cleaner.jpg",
  },

  // Baby Products (8 items)
  {
    id: 81,
    name: "Diapers",
    category: "baby",
    quantity: 20,
    notes: "Size 3, 32-count",
    image: "diapers.jpg",
  },
  {
    id: 82,
    name: "Baby Wipes",
    category: "baby",
    quantity: 25,
    notes: "Unscented, 80-count",
    image: "baby-wipes.jpg",
  },
  {
    id: 83,
    name: "Baby Formula",
    category: "baby",
    quantity: 15,
    notes: "Powder, 12.5oz",
    image: "formula.jpg",
  },
  {
    id: 84,
    name: "Baby Food",
    category: "baby",
    quantity: 35,
    notes: "Stage 2, assorted",
    image: "baby-food.jpg",
  },
  {
    id: 85,
    name: "Baby Shampoo",
    category: "baby",
    quantity: 12,
    notes: "Tear-free, 15oz",
    image: "baby-shampoo.jpg",
  },
  {
    id: 86,
    name: "Baby Lotion",
    category: "baby",
    quantity: 14,
    notes: "Hypoallergenic, 15oz",
    image: "baby-lotion.jpg",
  },
  {
    id: 87,
    name: "Pacifiers",
    category: "baby",
    quantity: 18,
    notes: "BPA-free, 2-pack",
    image: "pacifiers.jpg",
  },
  {
    id: 88,
    name: "Baby Bottles",
    category: "baby",
    quantity: 10,
    notes: "8oz, 3-pack",
    image: "baby-bottles.jpg",
  },

  // Pet Supplies (8 items)
  {
    id: 89,
    name: "Dog Food",
    category: "pets",
    quantity: 20,
    notes: "Dry kibble, 5lb bags",
    image: "dog-food.jpg",
  },
  {
    id: 90,
    name: "Cat Food",
    category: "pets",
    quantity: 25,
    notes: "Dry kibble, 3lb bags",
    image: "cat-food.jpg",
  },
  {
    id: 91,
    name: "Dog Treats",
    category: "pets",
    quantity: 18,
    notes: "Biscuits, 16oz",
    image: "dog-treats.jpg",
  },
  {
    id: 92,
    name: "Cat Treats",
    category: "pets",
    quantity: 15,
    notes: "Crunchy, 6oz",
    image: "cat-treats.jpg",
  },
  {
    id: 93,
    name: "Cat Litter",
    category: "pets",
    quantity: 12,
    notes: "Clumping, 14lb",
    image: "cat-litter.jpg",
  },
  {
    id: 94,
    name: "Pet Shampoo",
    category: "pets",
    quantity: 10,
    notes: "For dogs & cats, 16oz",
    image: "pet-shampoo.jpg",
  },
  {
    id: 95,
    name: "Pet Toys",
    category: "pets",
    quantity: 22,
    notes: "Assorted dog/cat toys",
    image: "pet-toys.jpg",
  },
  {
    id: 96,
    name: "Pet Bowls",
    category: "pets",
    quantity: 8,
    notes: "Stainless steel, 2-pack",
    image: "pet-bowls.jpg",
  },
];
